### ISSUE TITLE
Resolve the error from the product page.

### ISSUE THREAD

**Issue by deep1296** [harpreet-1/BeautyBlaze-Appointment-Booking-App#27]
- [ ] Not able to fetch the products.

<img width="949" alt="image" src="https://github.com/harpreet-1/BeautyBlaze-Appointment-Booking-App/assets/96063026/554c9ee3-a85a-4fcf-8b56-0ec589f52c14">

**Comment by harpreet-1** [comment]
done by harpreet singh
